models/expense.py
import sqlite3
from datetime import datetime, timedelta
class Expense:
    def __init__(self, id, user_id, amount, category, description, date):
        self.id = id
        self.user_id = user_id
        self.amount = amount
        self.category = category
        self.description = description
        self.date = date
    def get_expenses(user_id, page, size, filters, sort_by, sort_order):
        conn = sqlite3.connect('pig_save.db')
        cursor = conn.cursor()
        
        query = 'SELECT * FROM expenses WHERE user_id = ?'
        params = [user_id]
        
        if filters.get('category'):
            query += ' AND category = ?'
            params.append(filters['category'])
        
        if filters.get('start_date'):
            query += ' AND date >= ?'
            params.append(filters['start_date'])

        if filters.get('end_date'):
            query += ' AND date <= ?'
            params.append(filters['end_date'])

        if filters.get('min_amount'):
            query += ' AND amount >= ?'
            params.append(filters['min_amount'])

        if filters.get('max_amount'):
            query += ' AND amount <= ?'
            params.append(filters['max_amount'])
        
        params.extend([size, (page - 1) * size])
        query += f' ORDER BY {sort_by} {sort_order} LIMIT ? OFFSET ?'
        print(query)
        cursor.execute(query, params)

        expenses = cursor.fetchall()
        query_count = 'SELECT COUNT(*) FROM expenses WHERE user_id = ?'
        count_params = [user_id]
        
        if filters.get('category'):
            query_count += ' AND category = ?'
            count_params.append(filters['category'])
        
        if filters.get('start_date'):
            query_count += ' AND date >= ?'
            count_params.append(filters['start_date'])

        if filters.get('end_date'):
            query_count += ' AND date <= ?'
            count_params.append(filters['end_date'])

        if filters.get('min_amount'):
            query_count += ' AND amount >= ?'
            count_params.append(filters['min_amount'])

        if filters.get('max_amount'):
            query_count += ' AND amount <= ?'
            count_params.append(filters['max_amount'])
        total_expenses = conn.execute(query_count, count_params).fetchone()[0]
        conn.close()
        
        return expenses, total_expenses
    def add_expense(user_id, amount, category, description, date):
        conn = sqlite3.connect('pig_save.db')
        cursor = conn.cursor()
        cursor.execute("INSERT INTO expenses (user_id, amount, category, description, date) VALUES (?, ?, ?, ?, ?)",
                       (user_id, amount, category, description, date))
        conn.commit()
        conn.close()
    def update_expense(expense_id, amount, category, description, date):
        conn = sqlite3.connect('pig_save.db')
        cursor = conn.cursor()
        cursor.execute("UPDATE expenses SET  amount = ?, category = ?, description = ?, date = ? WHERE id = ?",
                       (amount, category, description, date, expense_id))
        conn.commit()
        conn.close()

    def delete_expense(expense_id):
        print(expense_id)
        conn = sqlite3.connect('pig_save.db')
        cursor = conn.cursor()
        cursor.execute(f"DELETE FROM expenses WHERE id = {expense_id}")
        conn.commit()
        conn.close()
        
    def get_report(user_id):
        conn = sqlite3.connect('pig_save.db')
        cursor = conn.cursor()
        now = datetime.now()
        cursor.execute("""
            SELECT SUM(amount) AS total
            FROM expenses
            WHERE strftime('%Y', date) = ? and user_id = ?
        """, (now.strftime('%Y'), user_id))
        total_year = ZeroIfNone(cursor.fetchone()[0])

        cursor.execute("""
        SELECT SUM(amount) AS total
        FROM expenses
        WHERE strftime('%m', date) = ? and user_id = ?
        """, (now.strftime('%m'), user_id))
        total_month = ZeroIfNone(cursor.fetchone()[0])
        
        start_of_week = (now - timedelta(days=now.weekday())).strftime('%Y-%m-%d')
        cursor.execute("""
            SELECT SUM(amount) AS total
            FROM expenses
            WHERE date >= ?
        """, (start_of_week,))
        total_week = ZeroIfNone(cursor.fetchone()[0])
        cursor.execute("""
        SELECT strftime('%Y-%m', date) AS month, SUM(amount) AS total
        FROM expenses
        WHERE strftime('%Y', date) = '2024' and user_id = ?
        GROUP BY month
        ORDER BY month
        """, (user_id,))
        line_data = [{'x': f'{row[0]}-01', 'y': row[1]} for row in cursor.fetchall()]

        cursor.execute("""
            SELECT category, SUM(amount) as total
            FROM expenses
            where user_id = ?
            GROUP BY category
            ORDER BY total DESC
        """, (user_id,))

        pie_data = [{'name': row[0], 'value': row[1]} for row in  cursor.fetchall()]
        conn.close()
        return line_data, pie_data, total_week, total_month, total_year
    def get_connection():
        conn = sqlite3.connect('pig_save.db')
        cursor = conn.cursor()
        return conn, cursor
def ZeroIfNone(input):
    if input is None:
        return 0
    else:
        return input

routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, Response,session
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from database import get_db_connection
from models.user import User
from models.expense import Expense
import models.family as Family
from functions.auth import auth_user
import math
import csv
import io
from core.currency_exchange import get_exchange_rate
from flask_babel import gettext as _
routes = Blueprint('main', __name__)
auth_routes = Blueprint('auth', __name__)

@routes.route('/')
def index():
    return render_template('index.html')

@auth_routes.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        name = request.form['name']
        confirm_password = request.form['confirm_password']

        if password != confirm_password:
            flash('Passwords do not match!', 'danger')
            return redirect(url_for('main.register'))
        
        hashed_password = generate_password_hash(password)
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute('SELECT * FROM users WHERE username = ?', (username,))
        existing_user = cursor.fetchone()

        if existing_user:
            flash('Username already exists. Please choose another.')
        else:
            cursor.execute('INSERT INTO users (username, name, password) VALUES (?, ?, ?)', 
                           (username, name, hashed_password))
            conn.commit()
            flash('Registration successful! You can now log in.')
            return redirect(url_for('auth.login'))
        
        conn.close()

    return render_template('auth/register.html')

@auth_routes.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        if auth_user(username, password):
            flash('Login successful!', 'success')
            return redirect(url_for('main.dashboard'))
        else:
            flash('Invalid credentials. Please try again.', 'danger')

    return render_template('auth/login.html')

@routes.route('/profile')
@login_required
def profile():
    return render_template('user/profile.html')

@routes.route('/update_language', methods=['POST'])
def update_language():
    language = request.form.get('language')
    if language:
        User.update_language(current_user.id, language)
        login_user(current_user, remember=True)
        flash("Language preference updated!", "success")
    return redirect(url_for('main.profile'))


@routes.route('/dashboard')
@login_required
def dashboard():
    line_data, pie_data, total_week, total_month, total_year = Expense.get_report(current_user.id)
    total_week = get_amount(float(total_week))
    total_month = get_amount(float(total_month))
    total_year = get_amount(float(total_year))
    return render_template('dashboard.html', user = current_user, line_data = line_data, pie_data = pie_data, total_week = total_week, total_month = total_month, total_year = total_year)

@routes.route('/expenses')
@login_required
def expenses():
    page = request.args.get('page', 1, type=int)
    page = request.args.get('page', 1, type=int)
    size = request.args.get('size', 5, type=int)
    user_id = request.args.get('user_id', current_user.id)
    sort_by = request.args.get('sort_by', 'date') 
    sort_order = request.args.get('sort_order', 'asc')  

    filters = {key: request.args.get(key) for key in ['category', 'start_date', 'end_date', 'min_amount', 'max_amount']}
    expenses, total_expenses = Expense.get_expenses(user_id, page, size, filters, sort_by, sort_order)
  
    total_pages = math.ceil(total_expenses / size)
    max_pages_displayed = 4
    start_page = max(1, page - 2)
    end_page = min(total_pages, start_page + max_pages_displayed - 1)

    if end_page - start_page < max_pages_displayed - 1:
        start_page = max(1, end_page - max_pages_displayed + 1)

    return render_template('expense/list.html', 
                           expenses=expenses,
                           page=page,
                           total_pages=total_pages,
                           end_page=end_page,
                           start_page=start_page,
                           filters=filters,
                           size=size,
                           sort_by=sort_by,
                           sort_order=sort_order)

@routes.route('/add_expense', methods=['POST'])
def add_expense():
    amount, category, description, date = [request.form[key] for key in ['amount', 'category', 'description', 'date']]
    page = request.form.get('page', 1, type=int)
    size = request.form.get('size', 5, type=int)
    filters = {key: request.form.get(key) for key in ['category', 'start_date', 'end_date', 'min_amount', 'max_amount']}
    Expense.add_expense(current_user.id, amount, category, description, date)
    flash('Expense added successfully!', 'success')
    return redirect(url_for('main.expenses', page=page, size=size))


@routes.route('/edit_expense', methods=['POST'])
def edit_expense():
    expense_id = request.form['expenseId']
    amount, category, description, date = [request.form[key] for key in ['amount', 'category', 'description', 'date']]
    filters = {key: request.form.get(key) for key in ['category_filter', 'start_date', 'end_date', 'min_amount', 'max_amount']}
    page = request.form.get('page', 1, type=int)
    size = request.form.get('size', 5, type=int)
    Expense.update_expense(expense_id, amount, category, description, date)
    return redirect(url_for('main.expenses', page=page, size=size))

#
@routes.route('/add_family', methods=['POST'])
def add_family():
    family_name = request.form['family_name']
    Family.add_family(family_name, current_user.id)
    return redirect(url_for('main.family'))

@routes.route('/add_member', methods=['POST'])
def add_member():
    name = request.form['member_name']
    f_id = request.form['family_id']
    result = Family.add_family_member(f_id, name)
    if result:
        flash("Family member added successfully.", 'success')
    else:
        flash("User not found.", 'danger')
    return redirect(url_for('main.family'))

@routes.route('/family')
@login_required
def family():
    families = Family.get_all_family(current_user.id)
    return render_template('family/family.html', families=families)

@routes.route('/export-expenses-csv')
def export_expenses_csv():
    sort_by = request.args.get('sort_by', 'date') 
    sort_order = request.args.get('sort_order', 'asc')  
    expenses = Expense.get_expenses(current_user.id, 1, 99999, dict(), sort_by, sort_order)
    output = io.StringIO()
    writer = csv.writer(output, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    
    writer.writerow(['Id', 'Category', 'Amount', 'Date', 'Description'])
    
    for expense in expenses[0]:
        writer.writerow([str(expense[0]), str(expense[1]), expense[2], expense[3], expense[4], expense[5]])
    
    output.seek(0) 

    return Response(
        output.getvalue(),
        mimetype='text/csv',
        headers={"Content-Disposition": "attachment;filename=expenses.csv"}
    )

@routes.route('/delete_expense/<int:expense_id>', methods=['DELETE'])
@login_required
def delete_expense(expense_id):
    Expense.delete_expense(expense_id)  
    flash('Expense deleted successfully!', 'success')
    return redirect(url_for('main.expenses'))

@routes.route('/update_currency', methods=['POST'])
@login_required
def update_currency():
    currency = request.form.get('currency')
    rate = get_exchange_rate()
    session['currency'] = currency
    session['rate'] = rate
    flash(f"Currency preference updated to {currency}!", "success")
    return redirect(url_for('main.dashboard'))

def get_amount(amount):
    currency = session.get('currency', 'VND')  
    if currency == 'USD':
        exchange_rate = session['rate']  
        return f"{'{:,.2f}'.format(amount / exchange_rate)} USD"  
    return f"{'{:,.0f}'.format(amount)} VND"

@routes.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('auth.login'))

templates/expense/add.html
<div id="expenseDialog" class="modal">
    <div class="modal-background"></div>
    Bạn thử bấm sdt mình nha: 0905690989
Mk: Denhoda12@
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title" id="dialogTitle">Add Expense</p>
            <button id="closeDialog" class="delete" ></button>
        </header>
        <section class="modal-card-body">
            <form id="expenseForm" method="post" action="{{ url_for('main.add_expense') }}">

                <input type="hidden" id="currentPage" name="page" value="{{ page }}">
                <input type="hidden" id="pageSize" name="size" value="{{ size }}">
                <input type="hidden" id="expenseId" name="expenseId" value="">
                <div class="field">
                    <label class="label" for="description">Description:</label>
                    <div class="control">
                        <input class="input" type="text" id="description" name="description" placeholder="Expense Description" required>
                    </div>
                </div>
                <div class="field">
                    <label class="label" for="amount">Amount:</label>
                    <div class="control">
                        <input class="input" type="number" id="amount" name="amount" step="1" placeholder="Expense Amount" required>
                    </div>
                </div>
                <div class="field">
                    <label class="label" for="date">Date:</label>
                    <div class="control">
                      <input class="input is-fullwidth custom-date-picker" type="date" id="dateAdd" name="date" required>
                    </div>
                  </div>
                <div class="field">
                    <label class="label" for="category">Category:</label>
                    <div class="control">
                        <div class="select is-fullwidth">
                            <select id="category" name="category" required>
                                <option value="">Select Category</option>
                                <option value="Food">Food</option>
                                <option value="Transport">Transport</option>
                                <option value="Entertainment">Entertainment</option>
                                <option value="Utilities">Utilities</option>
                                <option value="Others">Others</option>
                            </select>
                        </div>
                    </div>
                </div>
            </form>
        </section>
        <footer class="modal-card-foot">
            <button id="submitExpense" form="expenseForm" type="submit" class="button is-primary">Save Expense</button>
            <button class="button" id="cancelDialog">Cancel</button>
        </footer>
    </div>
</div>

<script>
    document.getElementById('openExpenseDialog').addEventListener('click', function() {
        openExpenseDialog('Add Expense', '', '', '', '', '', '{{ url_for("main.add_expense") }}');
    });

    document.getElementById('closeDialog').addEventListener('click', closeExpenseDialog);
    document.getElementById('cancelDialog').addEventListener('click', closeExpenseDialog);

    function closeExpenseDialog() {
        document.getElementById('expenseDialog').classList.remove('is-active');
        document.getElementById('expenseForm').reset();
    }

    function openExpenseDialog(title, id, description, amount, date, category, actionUrl) {
        
        document.getElementById('dialogTitle').textContent = title;
        document.getElementById('expenseId').value = id;
        document.getElementById('description').value = description;
        document.getElementById('amount').value = amount;
        document.getElementById('dateAdd').value = date;
        document.getElementById('category').value = category;
        document.getElementById('expenseForm').action = actionUrl;
        document.getElementById('expenseDialog').classList.add('is-active');
        document.getElementById('currentPage').value = '{{ page }}';
        document.getElementById('pageSize').value = '{{ size }}';
    }

    function editExpense(expenseId, description, category, date, amount) {
        openExpenseDialog('Edit Expense', expenseId, description, amount, date, category, '{{ url_for("main.edit_expense") }}');
    }

    document.querySelector('form[action="/add_expense"]').addEventListener('submit', function(event) {
        showToast('Expense added successfully!', 'success');
    });
    // load current date
    document.addEventListener('DOMContentLoaded', (event) => {
            const today = new Date().toISOString().split('T')[0];
            document.getElementById('dateAdd').value = today;
            console.log('as')
        });
    
</script>

templates/expense/list.html
{% extends "base.html" %}

{% block content %}
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-10">
        <h1 class="title has-text-centered is-3 mb-6">Expenses</h1>
        
        <div class="level">
          <div class="level-left">
            <div class="level-item">
              <h2 class="title is-4">Recent Expenses</h2>
            </div>
          </div>
          <div class="level-right">
            <div class="level-item">
              <button id="openExpenseDialog" class="button is-primary">
                <span class="icon">
                  <i class="fas fa-plus"></i>
                </span>
                <span>Add Expense</span>
              </button>
            </div>
          </div>
        </div>

        {% include 'expense/add.html' %}
        
       
          <form method="get" action="{{ url_for('main.expenses') }}" class="mb-5 filter-form">
            
            <div class="field is-grouped is-justify-content-space-between is-grouped-multiline is-flex-wrap-wrap">
                <div class="control">
                    <div class="select is-rounded">
                      <select name="size" id="size" onchange="this.form.submit()">
                        <option value="5" {% if size == 5 %}selected{% endif %}>5 per page</option>
                        <option value="10" {% if size == 10 %}selected{% endif %}>10 per page</option>
                        <option value="20" {% if size == 20 %}selected{% endif %}>20 per page</option>
                        <option value="50" {% if size == 50 %}selected{% endif %}>50 per page</option>
                      </select>
                    </div>
                  </div>
                <div class="control">
                  <div class="select">
                    <select name="category">
                        <option value="">Select Category</option>
                        <option value="Food">Food</option>
                        <option value="Transport">Transport</option>
                        <option value="Entertainment">Entertainment</option>
                        <option value="Utilities">Utilities</option>
                        <option value="Others">Others</option>
                    </select>
                  </div>
                </div>
                <div class="control">
                  <input class="input" type="date" name="start_date" value="{{ filters.start_date }}" placeholder="Start Date">
                </div>
                <div class="control">
                  <input class="input" type="date" name="end_date" value="{{ filters.end_date }}" placeholder="End Date">
                </div>
                <div class="control">
                  <input class="input" type="number" step="10000" name="min_amount" placeholder="Min Amount" value="{{ filters.min_amount }}">
                </div>
                <div class="control">
                  <input class="input" type="number" step="10000" name="max_amount" placeholder="Max Amount" value="{{ filters.max_amount }}">
                </div>
                
            </div>
            <div class="control is-flex is-justify-content-flex-end">
                <button type="submit" class="button is-info">Apply</button>
            </div>
            <div class="buttons">
              <a class="button is-primary" href="{{ url_for('main.export_expenses_csv') }}">
                  Export to CSV
              </a>
          </div>
            <nav class="pagination is-centered mt-6" role="navigation">
                <a class="pagination-previous" {% if page > 1 %}href="{{ url_for('main.expenses', page=page-1, size=size, sort_order=sort_order, sort_by=sort_by) }}"{% else %}disabled{% endif %}>Previous</a>
                <a class="pagination-next" {% if page < total_pages %}href="{{ url_for('main.expenses', page=page+1, size=size, sort_order=sort_order, sort_by=sort_by) }}"{% else %}disabled{% endif %}>Next page</a>
                <ul class="pagination-list">
                  {% for p in range(start_page, end_page + 1) %}
                    <li>
                      <a class="pagination-link {% if p == page %}is-current{% endif %}" href="{{ url_for('main.expenses', page=p, size=size, sort_order=sort_order, sort_by=sort_by) }}">{{ p }}</a>
                    </li>
                  {% endfor %}
                </ul>
              </nav>
            <div class="table-container">
              <table class="table is-striped is-hoverable is-fullwidth">
                <thead>
                    <tr>
                      <th>
                        Id
                      </th>
                      <th>
                        <a href="{{ url_for('main.expenses', sort_by='category', sort_order='desc' if sort_by == 'category' and sort_order == 'asc' else 'asc', page=page, size=size, **filters) }}">
                          Category
                        </a>
                      </th>
                      <th>
                        <a href="{{ url_for('main.expenses', sort_by='amount', sort_order='desc' if sort_by == 'amount' and sort_order == 'asc' else 'asc', page=page, size=size, **filters) }}">
                          Amount
                        </a>
                      </th>
                      <th>
                        <a href="{{ url_for('main.expenses', sort_by='date', sort_order='desc' if sort_by == 'date' and sort_order == 'asc' else 'asc', page=page, size=size, **filters) }}">
                            Date
                          </a>
                      </th>
                      <th>
                        <a href="{{ url_for('main.expenses', sort_by='description', sort_order='desc' if sort_by == 'description' and sort_order == 'asc' else 'asc', page=page, size=size, **filters) }}">
                          Description
                        </a>
                      </th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  
                  
                {% if expenses %}
                <tbody>
                  {% for expense in expenses %}
                    <tr>
                      <td>{{ expense[0] }}</td>
                     
                      <td>
                        <strong class="has-text-success">{{ expense[3] }}</strong>
                      </td>
                      <td>
                        <span class="tag is-primary is-light">{{ '{:,.0f}'.format(expense[2]) }}</span>
                      </td>
                      <td>{{ expense[5] }}</td>

                      <td>{{ expense[4] }}</td>
                      <td>
                        <div class="buttons are-small">
                            <button type="button" class="button is-info is-light" onclick="editExpense('{{ expense[0] }}', '{{ expense[4] }}', '{{ expense[3] }}', '{{ expense[5] }}', '{{ expense[2] }}')">Edit</button>
                            <button type="button" class="button is-danger is-light" onclick="deleteExpense('{{ expense[0] }}')">Delete</button>
                        </div>
                      </td>
                    </tr>
                  {% endfor %}
                  {% else %}
                  <td colspan="5" class="has-text-centered is-centered is-size-4 is-bold">No records</td>
                </div>
            {% endif %}
                </tbody>
              </table>
            </div>

            <nav class="pagination is-centered mt-6" role="navigation" >
              <a class="pagination-previous" {% if page > 1 %}href="{{ url_for('main.expenses', page=page-1, size=size, sort_order=sort_order, sort_by=sort_by) }}"{% else %}disabled{% endif %}>Previous</a>
              <a class="pagination-next" {% if page < total_pages %}href="{{ url_for('main.expenses', page=page+1, size=size, sort_order=sort_order, sort_by=sort_by) }}"{% else %}disabled{% endif %}>Next page</a>
              <ul class="pagination-list">
                {% for p in range(start_page, end_page + 1) %}
                  <li>
                    <a class="pagination-link {% if p == page %}is-current{% endif %}" href="{{ url_for('main.expenses', page=p, size=size, sort_order=sort_order, sort_by=sort_by) }}">{{ p }}</a>
                  </li>
                {% endfor %}
              </ul>
            </nav>
          
      </div>
    </div>
  </div>
</section>

<script>
  document.getElementById('openExpenseDialog').addEventListener('click', function() {
    document.getElementById('expenseDialog').classList.add('is-active');
  });

  document.getElementById('closeDialog').addEventListener('click', function() {
    document.getElementById('expenseDialog').classList.remove('is-active');
  });

  document.getElementById('cancelDialog').addEventListener('click', function() {
    document.getElementById('expenseDialog').classList.remove('is-active');
  });

  window.onclick = function(event) {
    var modal = document.getElementById('expenseDialog');
    if (event.target === modal) {
      modal.classList.remove('is-active');
    }
  };
  function deleteExpense(expenseId) {
    if (confirm('Are you sure you want to delete this expense?')) {
        fetch(`/delete_expense/${expenseId}`, {
            method: 'DELETE',
        })
        .then(response => {
              location.reload(); // Reload the page to reflect changes
        })
        .catch(error => {
            console.error('Error:', error);
            alert('An error occurred. Please try again.');
        });
    }
}

</script>
{% endblock %}