models/user.py
from flask_login import UserMixin
import sqlite3
class User(UserMixin):
    def __init__(self, id, username,name, language, age):
        self.id = id
        self.username = username
        self.name = name
        self.language = language
        self.age = age
        
    def getUser(user_id):
        conn = sqlite3.connect('pig_save.db')
        cursor = conn.cursor()
        cursor.execute('SELECT id, username, name, language, age FROM users WHERE id = ?', (user_id,))
        user = cursor.fetchone()
        conn.close()
        if user:
            return User(user[0], user[1], user[2], user[3], user[4])
        return None

    def update_language(user_id, language):
        conn = sqlite3.connect('pig_save.db')
        cursor = conn.cursor()
        cursor.execute("UPDATE users SET language = ? WHERE id = ?", (language, user_id))
        conn.commit()
        conn.close()

routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, Response,session
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from database import get_db_connection
from models.user import User
from models.expense import Expense
import models.family as Family
from functions.auth import auth_user
import math
import csv
import io
from core.currency_exchange import get_exchange_rate
from flask_babel import gettext as _
routes = Blueprint('main', __name__)
auth_routes = Blueprint('auth', __name__)

@routes.route('/')
def index():
    return render_template('index.html')

@auth_routes.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        name = request.form['name']
        confirm_password = request.form['confirm_password']

        if password != confirm_password:
            flash('Passwords do not match!', 'danger')
            return redirect(url_for('main.register'))
        
        hashed_password = generate_password_hash(password)
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute('SELECT * FROM users WHERE username = ?', (username,))
        existing_user = cursor.fetchone()

        if existing_user:
            flash('Username already exists. Please choose another.')
        else:
            cursor.execute('INSERT INTO users (username, name, password) VALUES (?, ?, ?)', 
                           (username, name, hashed_password))
            conn.commit()
            flash('Registration successful! You can now log in.')
            return redirect(url_for('auth.login'))
        
        conn.close()

    return render_template('auth/register.html')

@auth_routes.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        if auth_user(username, password):
            flash('Login successful!', 'success')
            return redirect(url_for('main.dashboard'))
        else:
            flash('Invalid credentials. Please try again.', 'danger')

    return render_template('auth/login.html')

@routes.route('/profile')
@login_required
def profile():
    return render_template('user/profile.html')

@routes.route('/update_language', methods=['POST'])
def update_language():
    language = request.form.get('language')
    if language:
        User.update_language(current_user.id, language)
        login_user(current_user, remember=True)
        flash("Language preference updated!", "success")
    return redirect(url_for('main.profile'))


@routes.route('/dashboard')
@login_required
def dashboard():
    line_data, pie_data, total_week, total_month, total_year = Expense.get_report(current_user.id)
    total_week = get_amount(float(total_week))
    total_month = get_amount(float(total_month))
    total_year = get_amount(float(total_year))
    return render_template('dashboard.html', user = current_user, line_data = line_data, pie_data = pie_data, total_week = total_week, total_month = total_month, total_year = total_year)

@routes.route('/expenses')
@login_required
def expenses():
    page = request.args.get('page', 1, type=int)
    page = request.args.get('page', 1, type=int)
    size = request.args.get('size', 5, type=int)
    user_id = request.args.get('user_id', current_user.id)
    sort_by = request.args.get('sort_by', 'date') 
    sort_order = request.args.get('sort_order', 'asc')  

    filters = {key: request.args.get(key) for key in ['category', 'start_date', 'end_date', 'min_amount', 'max_amount']}
    expenses, total_expenses = Expense.get_expenses(user_id, page, size, filters, sort_by, sort_order)
  
    total_pages = math.ceil(total_expenses / size)
    max_pages_displayed = 4
    start_page = max(1, page - 2)
    end_page = min(total_pages, start_page + max_pages_displayed - 1)

    if end_page - start_page < max_pages_displayed - 1:
        start_page = max(1, end_page - max_pages_displayed + 1)

    return render_template('expense/list.html', 
                           expenses=expenses,
                           page=page,
                           total_pages=total_pages,
                           end_page=end_page,
                           start_page=start_page,
                           filters=filters,
                           size=size,
                           sort_by=sort_by,
                           sort_order=sort_order)

@routes.route('/add_expense', methods=['POST'])
def add_expense():
    amount, category, description, date = [request.form[key] for key in ['amount', 'category', 'description', 'date']]
    page = request.form.get('page', 1, type=int)
    size = request.form.get('size', 5, type=int)
    filters = {key: request.form.get(key) for key in ['category', 'start_date', 'end_date', 'min_amount', 'max_amount']}
    Expense.add_expense(current_user.id, amount, category, description, date)
    flash('Expense added successfully!', 'success')
    return redirect(url_for('main.expenses', page=page, size=size))


@routes.route('/edit_expense', methods=['POST'])
def edit_expense():
    expense_id = request.form['expenseId']
    amount, category, description, date = [request.form[key] for key in ['amount', 'category', 'description', 'date']]
    filters = {key: request.form.get(key) for key in ['category_filter', 'start_date', 'end_date', 'min_amount', 'max_amount']}
    page = request.form.get('page', 1, type=int)
    size = request.form.get('size', 5, type=int)
    Expense.update_expense(expense_id, amount, category, description, date)
    return redirect(url_for('main.expenses', page=page, size=size))

#
@routes.route('/add_family', methods=['POST'])
def add_family():
    family_name = request.form['family_name']
    Family.add_family(family_name, current_user.id)
    return redirect(url_for('main.family'))

@routes.route('/add_member', methods=['POST'])
def add_member():
    name = request.form['member_name']
    f_id = request.form['family_id']
    result = Family.add_family_member(f_id, name)
    if result:
        flash("Family member added successfully.", 'success')
    else:
        flash("User not found.", 'danger')
    return redirect(url_for('main.family'))

@routes.route('/family')
@login_required
def family():
    families = Family.get_all_family(current_user.id)
    return render_template('family/family.html', families=families)

@routes.route('/export-expenses-csv')
def export_expenses_csv():
    sort_by = request.args.get('sort_by', 'date') 
    sort_order = request.args.get('sort_order', 'asc')  
    expenses = Expense.get_expenses(current_user.id, 1, 99999, dict(), sort_by, sort_order)
    output = io.StringIO()
    writer = csv.writer(output, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    
    writer.writerow(['Id', 'Category', 'Amount', 'Date', 'Description'])
    
    for expense in expenses[0]:
        writer.writerow([str(expense[0]), str(expense[1]), expense[2], expense[3], expense[4], expense[5]])
    
    output.seek(0) 

    return Response(
        output.getvalue(),
        mimetype='text/csv',
        headers={"Content-Disposition": "attachment;filename=expenses.csv"}
    )

@routes.route('/delete_expense/<int:expense_id>', methods=['DELETE'])
@login_required
def delete_expense(expense_id):
    Expense.delete_expense(expense_id)  
    flash('Expense deleted successfully!', 'success')
    return redirect(url_for('main.expenses'))

@routes.route('/update_currency', methods=['POST'])
@login_required
def update_currency():
    currency = request.form.get('currency')
    rate = get_exchange_rate()
    session['currency'] = currency
    session['rate'] = rate
    flash(f"Currency preference updated to {currency}!", "success")
    return redirect(url_for('main.dashboard'))

def get_amount(amount):
    currency = session.get('currency', 'VND')  
    if currency == 'USD':
        exchange_rate = session['rate']  
        return f"{'{:,.2f}'.format(amount / exchange_rate)} USD"  
    return f"{'{:,.0f}'.format(amount)} VND"

@routes.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('auth.login'))

templates/user/profile.html
{% extends "base.html" %} 
{% block css %}

<style>
    .profile-picture {
        border-radius: 50%;
        width: 150px;
        height: 150px;
        object-fit: cover;
        border: 3px solid #00d1b2; /* Adds a border to the profile picture */
        margin-bottom: 10px;
    }
   
</style>
{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title">My Profile</h1>
        <div class="profile-header">
            <div class="columns is-centered">
                <div class="column has-text-centered">
                    <img src="https://via.placeholder.com/150" alt="Profile Picture" class="profile-picture">
                    <h2 class="title">{{ current_user.name }}</h2>
                    <p class="subtitle">@kunwalle</p>
                </div>
            </div>
        </div>
        <div class="profile-info">
            <div class="columns">
                <div class="column is-half">
                    <div class="box">
                        <h3 class="subtitle">Basic Information</h3>
                        <p><strong>Email:</strong> {{ current_user.email }}</p>
                        <p><strong>Phone:</strong> {{ current_user.phone }}</p>
                        <p><strong>Address:</strong> {{ current_user.address }}</p>
                        <form action="{{ url_for('main.update_language') }}" method="POST">
                            <div class="field">
                                <label class="label" for="language">Preferred Language:</label>
                                <div class="control">
                                    <div class="select">
                                        <select id="language" name="language">
                                            <option value="en" {% if current_user.language == 'en' %}selected{% endif %}>English</option>
                                            <option value="vi" {% if current_user.language == 'vi' %}selected{% endif %}>Vietnamese</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="field">
                                <div class="control">
                                    <button type="submit" class="button is-link">Save</button>
                                </div>
                            </div>
                        </form>
                        
                    </div>
                </div>
                <div class="column is-half">
                    <div class="box">
                        <h3 class="subtitle">About Me</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam imperdiet euismod urna, a tempus libero commodo eget.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}